name: ${project.name}
version: ${project.buildversion}
description: ${project.name}

authors: [RiotSeb]
website: github.com/RiotSeb

depend: [WorldGuard]

main: de.riotseb.worldguardzones.Main

commands:
  find: